#pragma once
#define DYNAMIC_MACRO_NESTING
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 250
