# Enabled settings
LTO_ENABLE = yes
LEADER_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
RGBLIGHT_ENABLE = yes

# Disabled settings
MOUSEKEY_ENABLE = no
TERMINAL_ENABLE = no
CONSOLE_ENABLE = no
KEY_LOCK_ENABLE = no
AUTO_SHIFT_MODIFIERS = no
AUDIO_ENABLE = no
