EXTRAFLAGS += -flto

# Enabled settings
MOUSEKEY_ENABLE = yes
RGBLIGHT_ENABLE = yes
LEADER_ENABLE = yes

# Disabled settings
TERMINAL_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
CONSOLE_ENABLE = no
KEY_LOCK_ENABLE = no
AUTO_SHIFT_MODIFIERS = no
AUDIO_ENABLE = no
