EXTRAFLAGS += -flto
MOUSEKEY_ENABLE = yes
DYNAMIC_MACRO_ENABLE = no
RGBLIGHT_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = no
AUDIO_ENABLE = no
AUTO_SHIFT_ENABLE = no
MIDI_ENABLE = no
TERMINAL_ENABLE = no

